### ISSUE TITLE
Result bar display on non-presidential races

### ISSUE THREAD

**Issue by audreycarlsen** [nprapps/elections20-primaries#86]
Result bars extend further across the table for presidential results than for other races. For the other races, this looks visually misleading and inconsistent.

**Comment by thomaswilburn** [comment]
We can't get 100% the same display because the columns and construction of these two are different (results-table is an actual table, and those aren't allowed to be position: relative for setting up our bar). However, I extended the results bar to max out at 100% of the name column width, which should reduce the visible discrepancy between the two.
